version: "3"

services:
  db:
    image: mysql
    container_name: mysql-server
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"

  web:
    container_name: django_server
    build:
      context: .
      dockerfile: dockerfile
    # environment:
    volumes:
      - .:/server
    # working_dir: /gongcheck/
    depends_on:
      - db
    ports:
      - 8000:8000
    command: bash -c "
      python3 ./gongcheck/manage.py migrate &&
      python3 ./gongcheck/manage.py runserver 0.0.0.0:8000
      "
