# Generated by Django 3.2.4 on 2023-05-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='student_id',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
