# Generated by Django 3.2.4 on 2023-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230515_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': '교수', 'verbose_name_plural': '교수'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '학생', 'verbose_name_plural': '학생'},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='usernumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='usernumber',
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='교번'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='학번'),
        ),
    ]
