version: "3"

services:
  db:
    container_name: mysql-server
    image: mysql:5.7
    # platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    container_name: django_server
    build: .
    # environment:
    volumes:
      - .:/app
    # working_dir: /gongcheck/
    command: bash -c "
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  db_data:
