# Generated by Django 3.2.4 on 2023-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attend', models.BooleanField()),
                ('course_number', models.IntegerField()),
            ],
        ),
    ]
