# Generated by Django 3.2.4 on 2023-05-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freq', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='activation_duration',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
