# Generated by Django 3.2.4 on 2023-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freq', '0003_audiofile_activation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='course_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
