# Generated by Django 3.2.4 on 2023-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freq', '0004_auto_20230524_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
    ]
