# Generated by Django 3.2.4 on 2023-05-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor_id',
            field=models.CharField(max_length=10),
        ),
    ]
