name: Docker Compose

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        docker build -t gongcheck ./gongcheck
    
    - name: DockerHub Login
      run: |
        echo "${{ secrets.DOCKERHUB_PW }}" | docker login --username "${{ secrets.DOCKERHUB_ID }}" --password-stdin

    - name: Push to Docker Hub
      run: |
        docker tag gongcheck:latest "${{ secrets.DOCKERHUB_ID }}/gongcheck:latest"
        docker push "${{ secrets.DOCKERHUB_ID }}/gongcheck:latest"

    - name: Docker Compose
      run: |
        cd ./gongcheck
        docker-compose up -d

    - name: Make logs
      run: |
        cd ./gongcheck
        docker-compose logs
