name: Docker Compose

on:
  push:
    branches:
      - actions  # 또는 사용하는 기본 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 코드
      uses: actions/checkout@v2

    - name: Docker Compose 빌드 및 실행
      uses: docker/compose-cli-action@v0.9.0
      with:
        compose-file: gongcheck/docker-compose.yaml
        compose-command: up -d  # 또는 필요한 다른 Docker Compose 명령

    - name: 작업 완료 후 컨테이너 로그 표시 (옵션)
      run: docker-compose logs
