name: Docker Compose

on:
  push:
    branches:
      - actions  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        working-directory: ./gongcheck
        docker build -t gongcheck .
    
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      run: |
        docker tag my-app:latest "${{ secrets.DOCKERHUB_USERNAME }}/gongcheck:latest"
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/gongcheck:latest"

    - name: Docker Compose
      run: |
        working-directory: ./gongcheck
        docker-compose up -d

    - name: Make logs
      run: |
        working-directory: ./gongcheck
        docker-compose logs
