name: Docker Compose

on:
  push:
    branches:
      - actions  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run Docker Compose
      run: |
        gongcheck/docker-compose up -d

    - name: Display container logs after completion (optional)
      run: |
        docker-compose logs
